version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4

jobs:
  sync-lint:
    docker:
      - image: cimg/python:3.8.12

    working_directory: ~/timeserio

    environment:  # these don't get interpolated
        POETRY_VERSION: 1.1.2 
        POETRY_HOME: /home/circleci/.poetry
        POETRY_VIRTUALENVS_IN_PROJECT: "true"

    steps:
      - checkout

      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - pip-packages-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "poetry.lock" }}
            - pip-packages-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-
            - pip-packages-{{ .Environment.CACHE_VERSION }}-

      - run:
          name: Set up build tools
          command: |
            mkdir -p $POETRY_HOME
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
            cat $POETRY_HOME/env >> $BASH_ENV

      - run:
          # we remove untracked to avoid issues with stail/removed dependencies
          name: Install dependencies
          command: |
            poetry install -vvv --remove-untracked

      - save_cache:
          paths:
              - ./.venv/
          key: pip-packages-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "poetry.lock" }}

      - run:
          name: Run lint
          command: |
            make lint

      - persist_to_workspace:
          root: /home/circleci  # absolute, or relative from working directory
          paths:  # Must be relative path from root
            - timeserio/.venv
            - .poetry

  test:
    docker:
      - image: cimg/python:3.8.12
    parallelism: 4

    working_directory: ~/timeserio

    environment:
        POETRY_VIRTUALENVS_IN_PROJECT: "true"

    steps:

      - checkout

      - attach_workspace:
          at: /home/circleci  # Must be absolute path or relative path from working_directory

      - run:
          name: Configure poetry
          command: cat ~/.poetry/env >> $BASH_ENV

      - run:
          name: Run tests
          command:  |
            TESTFILES=$(circleci tests glob "tests/**/*.py" | circleci tests split --split-by=timings)
            poetry run pytest --cov=./timeserio/ --cov-report xml --junitxml=junit/pytest/results.xml --keep-duplicates $TESTFILES
      
      - store_test_results:
          path: ./junit

      - codecov/upload:
          file: ./coverage.xml
  
  doctest:
    docker:
      - image: cimg/python:3.8.12

    working_directory: ~/timeserio

    environment:
        POETRY_VIRTUALENVS_IN_PROJECT: "true"

    steps:

      - checkout

      - attach_workspace:
          at: /home/circleci  # Must be absolute path or relative path from working_directory

      - run:
          name: Configure poetry
          command: cat ~/.poetry/env >> $BASH_ENV


      - run:
          name: Run doctests
          command: make doctest

      # - codecov/upload:
      #     file: ./coverage.xml

  build-release-test:
    docker:
      - image: cimg/python:3.8.12

    working_directory: ~/timeserio

    environment:
        TWINE_NON_INTERACTIVE: "true"

    steps:

      - checkout

      - attach_workspace:
          at: /home/circleci  # Must be absolute path or relative path from working_directory

      - run:
          name: Configure poetry
          command: cat ~/.poetry/env >> $BASH_ENV

      - run:
          name: Create source and wheel distribution
          command: |
            make package

      - run:
          name: Release to PyPI
          command: |
            TWINE_REPOSITORY_URL=${TEST_TWINE_REPOSITORY_URL} \
            TWINE_USERNAME=${TEST_TWINE_USERNAME} \
            TWINE_PASSWORD=${TEST_TWINE_PASSWORD} \
            make release

      - persist_to_workspace:
          root: .
          paths: 
            - ./build

  release-prod:
    docker:
      - image: cimg/python:3.8.12

    working_directory: ~/timeserio

    environment:
        TWINE_NON_INTERACTIVE: "true"
        POETRY_VIRTUALENVS_IN_PROJECT: "true"

    steps:

      - checkout

      - attach_workspace:
          at: /home/circleci  # Must be absolute path or relative path from working_directory

      - run:
          name: Configure poetry
          command: cat ~/.poetry/env >> $BASH_ENV
          
      - run:
          name: Release to PyPI
          command: |
            TWINE_REPOSITORY_URL=${PROD_TWINE_REPOSITORY_URL} \
            TWINE_USERNAME=${PROD_TWINE_USERNAME} \
            TWINE_PASSWORD=${PROD_TWINE_PASSWORD} \
            make release

  docs-build:
    docker:
      - image: cimg/python:3.8.12

    working_directory: ~/timeserio

    environment:
        POETRY_VIRTUALENVS_IN_PROJECT: "true"

    steps:

      - checkout

      - run:
          name: Install pandoc
          command: |
            sudo wget https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb
            sudo dpkg -i pandoc-2.7.3-1-amd64.deb

      - attach_workspace:
          at: /home/circleci  # Must be absolute path or relative path from working_directory

      - run:
          name: Configure poetry
          command: cat ~/.poetry/env >> $BASH_ENV

      - run:
          name: Build sphinx docs
          command:  |
            make docs-build
      
      - persist_to_workspace:
          root: docs/_build
          paths: 
            - html

  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - add_ssh_keys:  # add deploy key to allow write access
          fingerprints:
            - "82:11:ce:1f:00:9b:90:10:54:9c:e4:d7:dc:6c:0a:c1"
      - checkout      
      - attach_workspace:
          at: docs/_build
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "techmonitoring@octopus.energy"
            git config user.name "octo-ci"
      - run:
          name: Deploy docs to gh-pages branch
          command: |
            touch docs/_build/html/.nojekyll
            gh-pages --dist docs/_build/html --dotfiles --branch gh-pages --message "Update sphinx html docs [ci skip]"

workflows:
  version: 2
  lint-test-docs:
    jobs:
      - sync-lint:
          filters:
              tags:
                only: /^\d+\.\d+\.\d+$/
      - test:
          requires:
            - sync-lint
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
      - doctest:
          requires:
            - sync-lint
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
      - build-release-test:
          requires:
            - test
            - doctest
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - release-prod:
          requires:
            - build-release-test
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - docs-build:
          requires:
            - test
            - doctest
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - docs-deploy:
          requires:
            - docs-build
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
